# Generated by Django 5.2.4 on 2025-10-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=70, unique=True)),
                ("email", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="User_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=40)),
                ("user_surname", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=200)),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True, related_name="liked_projects", to="api.user"
                    ),
                ),
                (
                    "user_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="api.user_info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
                ("followers", models.IntegerField(default=0)),
                (
                    "user_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="api.user_info",
                    ),
                ),
            ],
        ),
    ]
