# Generated by Django 5.2.4 on 2025-10-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=128, unique=True)),
                ("nickname", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("user_name", models.CharField(max_length=40)),
                ("user_surname", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="User_Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=40)),
                ("project_description", models.CharField(max_length=200)),
                ("views", models.IntegerField(default=0)),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True, related_name="liked_projects", to="api.user"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
