# Generated by Django 5.2.4 on 2025-10-05 19:07

import api.models.model_user.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.model_user.user.CustomUserManager()),
            ],
        ),
    ]
